### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by rd15armas** [bg2bhc/gr-dslwp#1]
Hello
I have get these error: Could you show me how to fix it.
Thnks.

hp@hp:~/sdr/gr-dslwp/build$ sudo make 
Scanning dependencies of target gnuradio-dslwp
[  2%] Building CXX object lib/CMakeFiles/gnuradio-dslwp.dir/fft_estimator_cc_impl.cc.o
/home/hp/sdr/gr-dslwp/lib/fft_estimator_cc_impl.cc: In member function ‘virtual int gr::dslwp::fft_estimator_cc_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/hp/sdr/gr-dslwp/lib/fft_estimator_cc_impl.cc:136:19: error: lvalue required as left operand of assignment
      sum.real() = 0.0f;
                   ^~~~
/home/hp/sdr/gr-dslwp/lib/fft_estimator_cc_impl.cc:137:19: error: lvalue required as left operand of assignment
      sum.imag() = 0.0f;
                   ^~~~
/home/hp/sdr/gr-dslwp/lib/fft_estimator_cc_impl.cc:141:36: error: lvalue required as left operand of assignment
       coeff.real() = cos(-phase_acc);
                                    ^
/home/hp/sdr/gr-dslwp/lib/fft_estimator_cc_impl.cc:142:36: error: lvalue required as left operand of assignment
       coeff.imag() = sin(-phase_acc);
                                    ^
lib/CMakeFiles/gnuradio-dslwp.dir/build.make:206: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/fft_estimator_cc_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/fft_estimator_cc_impl.cc.o] Error 1
CMakeFiles/Makefile2:137: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bg2bhc** [comment]
Hi, 

I did not get this error here, maybe different version of gnuradio we used?

Please have a try to replace sum.real() with *((float *)&sum) and sum.imag() with *(((float *)&sum)+1)

Thank you for your report!
