### ISSUE TITLE
Missing Blocks

### ISSUE THREAD

**Issue by cpbridges** [bg2bhc/gr-dslwp#11]
Hi BG2BHC,

I've installed gr-lilacsat and gr-dswlp but find the demodulator grc files have some blocks missing. What dependancy/block is missing here.

Getting setup for the next few hours to receive in UK, 73s Chris

![screenshot from 2018-05-31 14-05-55](https://user-images.githubusercontent.com/2065141/40784007-2b3c5568-64dc-11e8-8ff4-88d45595ee51.png)

**Comment by bg2bhc** [comment]
Hi Chris, fft_correlator_hier is a hier block and the grc is included in hier block (described in readme). interface_wxs_tm_converter_dslwp is disabled so please do not mind.

**Comment by cpbridges** [comment]
Yes, got it now.
