### ISSUE TITLE
Error installing GR-DSLWP

### ISSUE THREAD

**Issue by lu1hko** [bg2bhc/gr-dslwp#14]
lu1hko@lu1hko-All-Series:~/Descargas/gr-dslwp-master/build$ sudo make
[sudo] contraseña para lu1hko: 
Scanning dependencies of target gnuradio-dslwp
[  2%] Building CXX object lib/CMakeFiles/gnuradio-dslwp.dir/lrtc_mod_bc_impl.cc.o
/home/lu1hko/Descargas/gr-dslwp-master/lib/lrtc_mod_bc_impl.cc: In member function ‘virtual int gr::dslwp::lrtc_mod_bc_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/lu1hko/Descargas/gr-dslwp-master/lib/lrtc_mod_bc_impl.cc:108:93: error: lvalue required as left operand of assignment
           out[i*256+j].real() = asm32[j].real() * cos(d_pacc) - asm32[j].imag() * sin(d_pacc);
                                                                                             ^
/home/lu1hko/Descargas/gr-dslwp-master/lib/lrtc_mod_bc_impl.cc:109:93: error: lvalue required as left operand of assignment
           out[i*256+j].imag() = asm32[j].real() * sin(d_pacc) + asm32[j].imag() * cos(d_pacc);
                                                                                             ^
lib/CMakeFiles/gnuradio-dslwp.dir/build.make:734: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/lrtc_mod_bc_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/lrtc_mod_bc_impl.cc.o] Error 1
CMakeFiles/Makefile2:174: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Kerry-Huang** [comment]
#16
