### ISSUE TITLE
Compile failure on new install of Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by m0nux** [bg2bhc/gr-dslwp#18]
Hi!
I am trying to follow instructions from Live CD User Manual  3.2 Install but compiling keeps failing with this error:

/home/julian/gr-dslwp/lib/lrtc_mod_bc_impl.cc: In member function ‘virtual int gr::dslwp::lrtc_mod_bc_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/julian/gr-dslwp/lib/lrtc_mod_bc_impl.cc:108:93: error: lvalue required as left operand of assignment
           out[i*256+j].real() = asm32[j].real() * cos(d_pacc) - asm32[j].imag() * sin(d_pacc);
                                                                                             ^
/home/julian/gr-dslwp/lib/lrtc_mod_bc_impl.cc:109:93: error: lvalue required as left operand of assignment
           out[i*256+j].imag() = asm32[j].real() * sin(d_pacc) + asm32[j].imag() * cos(d_pacc);
                                                                                             ^
lib/CMakeFiles/gnuradio-dslwp.dir/build.make:734: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/lrtc_mod_bc_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/lrtc_mod_bc_impl.cc.o] Error 1
CMakeFiles/Makefile2:174: recipe for target 'lib/CMakeFiles/gnuradio-dslwp.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-dslwp.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

The caret in red is point up at the right bracket of this expression cos(d_pacc) 
I know very little (nothing!) about Linux so this may be my fault :( 
Can anyone point me in the right direction please?
TIA, Julian

**Comment by daniestevez** [comment]
Try the fix in this PR https://github.com/bg2bhc/gr-dslwp/pull/17

**Comment by m0nux** [comment]
Many thanks - I'll try it.

**Comment by m0nux** [comment]
That allowed it to compile - thank you :)
