### ISSUE TITLE
.raw Sample File please?

### ISSUE THREAD

**Issue by K4KDR** [bg2bhc/gr-dslwp#3]
Wonderful work!! So exciting to see the frontend and proxy apps.  Best of luck with the launch.

Would it be possible to get a .raw sample file so that our install of the decoders could be tested with the REPLAY flowgraph?

Many thanks!

-Scott,  K4KDR

**Comment by bg2bhc** [comment]
Hi Scott, please find the sample file here:
https://1drv.ms/u/s!Av6J6WjI3UbMhHWVF5N2PY_tgPRn

2018-05-18 13:55 GMT+08:00 K4KDR <notifications@github.com>:

**Comment by K4KDR** [comment]
Thank you!  However, at that URL I get the following:

-------
```
This item might not exist or is no longer available

This item might have been deleted, expired, or you might not have permission to view it.
 Contact the owner of this item for more information.
```
-----

**Comment by bg2bhc** [comment]
Hi Scott, please check the sample file here:
https://drive.google.com/file/d/1YoymkdXI81-h907Vsgxbb1jZV5ZtPNpz/view

2018-05-20 7:19 GMT+08:00 K4KDR <notifications@github.com>:

**Comment by K4KDR** [comment]
Wonderful!  Thank you so much.
