### ISSUE TITLE
New Issue observed

### ISSUE THREAD

**Issue by N6RFM** [bg2bhc/gr-dslwp#4]
From today's update

Executing: /usr/bin/python2 -u /home/bob/gr-dslwp-master/examples/demod_dslwp_gmsk_b1_250bps_0r5_coherent.py

**** Program tracking
Set home location in ECEF: 1532.291327, -4518.180559, 4218.900517

>>> Done

No longer can run decoders in example file.  Please advise.  Thanks.  Bob N6RFM

**Comment by bg2bhc** [comment]
Hi bob, there is a new block called Program Tracking CC in place of Plan13 CC, and there is a path to an txt in the example folder, and should be edited according to your path for gr-dslwp. Will update this to readme. Thank you very much!

**Comment by N6RFM** [comment]
Thanks Wei.  That fixed it, of course.  There are two A0 and two B0
demodulators - is there any advice on which ones to try, since things are
set up for one A0 and 0ne B0 at a time?

BTW, I'll be going to Baltimore tomorrow, but back Sunday midday our time
so as to be ready Sunday night East coast time to listen!

Best,

Bob

**Comment by bg2bhc** [comment]
Hi Bob, almost forgot that! Thank you very much for reminder!

6 different demod GRCs are provided for differnet frequencies and modes. After sepration, the following GRCs should be used:
- demod_dslwp_gmsk_a0_500bps_0.25_dpd.grc (Satellite A Radio 0, 500 bps GMSK with 1/4 Turbo code)
- demod_dslwp_gmsk_a1_250bps_0.5_coherent.grc (Satellite A Radio 1, 250 bps GMSK with 1/2 Turbo code and precoder)
- demod_dslwp_gmsk_b0_500bps_0.25_dpd.grc (Satellite B Radio 0, 500 bps GMSK with 1/4 Turbo code)
- demod_dslwp_gmsk_b1_250bps_0.5_coherent.grc (Satellite B Radio 1, 250 bps GMSK with 1/2 Turbo code and precoder)

Also add this information to readme.

**Comment by N6RFM** [comment]
Thanks Wei.  

Bob M.
