### ISSUE TITLE
2 different compilation issues

### ISSUE THREAD

**Issue by darkstar007** [bg2bhc/gr-dslwp#5]
On a modern gcc/g++ there are two issues:
1) A.real() = B; is not a valid statement. These need to be replaced with A.real(B); This error is generated in a number of files

2) In fec_encode_b_impl.cc there are a pair of lines of the form:
```
char msg_ptt_on[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x01, 0xFD};
```
this is not valid as it contains values higher than 0x7F and hence the lines need to be changed  to
```
unsigned char msg_ptt_on[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x01, 0xFD};
```

Thanks,

Matt

**Comment by jhm776** [comment]
I cloned the repo today (05/28/18) and then had to fix these issues.

**Comment by jhm776** [comment]
added (actually Devuan, not Debian):
Linux gradio 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
